### ISSUE TITLE
No HTTPS

### ISSUE THREAD

**Issue by kn0wmad** [kn0wmad/osa#6]
The current setup is just a DNS link to the ipfs.io gateway, which does not allow visitors to the site to use HTTPS, which is best practice and now widely default.  This will break the site for many users.  Fixes will be implemented by the end of 2020.

**Comment by nuke-web3** [comment]
I use https://pinata.cloud for hosting https://cryptorado.org/, they use cloudflare gateway in the back end.

You can add this domain by following the "Connecting Your Website" instructions at the bottom of this page: https://www.cloudflare.com/distributed-web-gateway/

More info here: https://developers.cloudflare.com/distributed-web/ipfs-gateway

**Comment by nuke-web3** [comment]
pro tip for pinata, you just need to use the "folder upload" for the directory containing `index.html` and **don't** wrap it in a unix-like directory. 
![image](https://user-images.githubusercontent.com/35669742/102125870-890dac80-3e07-11eb-957c-0005dee71884.png)

**Comment by kn0wmad** [comment]
> I use https://pinata.cloud for hosting https://cryptorado.org/, they use cloudflare gateway in the back end.
> 
> You can add this domain by following the "Connecting Your Website" instructions at the bottom of this page: https://www.cloudflare.com/distributed-web-gateway/
> 
> More info here: https://developers.cloudflare.com/distributed-web/ipfs-gateway

Hey Dan,
Thank you very much for your suggestion.  I did look into using CF's Argo Tunnel as well as Pinata.  I am currently setting up a self-hosted solution and the IPFS version of the site will be a well-advertised backup.  I like the idea of having a foot in each domain, so to speak.

CryptoColorado looks great by the way!

**Comment by nuke-web3** [comment]
Ah thanks man! Cryptorado is fun to play with Vue tooling for sure.

IMHO, having_many_ hosts for your site is best. Why not use a free cloud based service in addition to self hosting? For instance, if you publish the CID for any publishes, I would be happy to pin it :) 

Also have you seen https://github.com/ipfs-shipyard/ipfs-cohost that makes this kinda of thing easy?
As well as https://cluster.ipfs.io/ ? 

If you are interested, I would be down to experiment with these tools, I have not used them directly myself, and would be down to try for your site and the cryptorado one

**Comment by kn0wmad** [comment]
> IMHO, having_many_ hosts for your site is best. Why not use a free cloud based service in addition to self hosting? For instance, if you publish the CID for any publishes, I would be happy to pin it :)

Yeah, definitely.  Do you know a way to automate updates to those that pin your content though?  I'm just learning IPFS tooling so I'm sure we'll mess around with it soon.  I'll check those tools out tomorrow.  I was looking at your cryptorado node specifically, but we'll chat very soon

**Comment by kn0wmad** [comment]
I think this is also relevant - https://developers.cloudflare.com/distributed-web/ipfs-gateway/troubleshooting#the-nodes-with-the-requested-content-are-not-publicly-addressable - as even when it functions the loading is very slow

**Comment by kn0wmad** [comment]
I'm going to close this as it is technically fixed using cloudflare's gateway w/ https support.  Thanks Dan.
